package Subset;

public enum MilitaryRank {
    WARRANT_OFFICER_1,
    CHIEF_WARRANT_OFFICER_2,
    CHIEF_WARRANT_OFFICER_3,
    CHIEF_WARRANT_OFFICER_4,
    CHIEF_WARRANT_OFFICER_5,
    SECOND_LIEUTENANT,
    FIRST_LIEUTENANT,
    CAPTAIN,
    MAJOR,
    LIEUTENANT_COLONEL,
    COLONEL,
    BRIGADIER_GENERAL,
    MAJOR_GENERAL,
    LIEUTENANT_GENERAL,
    GENERAL,
    GENERAL_OF_THE_ARMY
}
